baseURL = "https://example.docsy.dev"
title = "Goldydocs"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true
enableGitInfo = false
# Taxonomies
# taxonomies = { tag = "tags", category = "categories" }

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
  blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

# Language configuration
[languages]
  [languages.en]
    languageName = "English"
    title = "Goldydocs"
    [languages.en.params]
      description = "A Docsy example site"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute.block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

[outputs]
  section = ["HTML", "print", "RSS"]

[params]
  offlineSearch = true

  [params.taxonomy]
    taxonomyCloud = ["tags", "categories"]
    taxonomyCloudTitle = ["Tag Cloud", "Categories"]
    taxonomyPageHeader = ["tags", "categories"]

  [params.ui]
    breadcrumb_disable = false
    navbar_logo = true
    navbar_translucent_over_cover_disable = false
    sidebar_menu_compact = true
    sidebar_search_disable = false
    ul_show = 1
    sidebar_menu_foldable = true
    sidebar_cache_limit = 1000

  [params.ui.readingtime]
    enable = true

  
  
[module]
  hugoVersion = { extended = true, min = "0.110.0" }
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
